### ISSUE TITLE
Exhibit URLs

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/Sitemap#2]
The Sitemap lists exhibit URLs as "http://exhibits.library.ucsc.edu/exhibit/show/3" ".../show/7" etc. but all of these pages lead to 404 errors.

Should these URLs be redirecting to the human-readable exhibit URLs? (eg. http://exhibits.library.ucsc.edu/exhibits/show/what-is-a-book)

Same issue with the Collection URLs

**Comment by JessWaggs** [comment]
I think the best practice is to use final URLs in a sitemap rather than redirects. Any way to put the final URLs in the sitemap instead?

**Comment by NedHenry** [comment]
The most recent commit fixes these issues. The issue came up because the URLs for collections identify the collection by ID number, but those for exhibits use the name of the exhibit in the URL. Both are now handled correctly by the plugin.
